* MawsonLakes.Org SkyWater 

This repository contains the files and documentation for production of as ASIC
via the Google and Skywater shuttle program.

** Tools / Installation

These files were created using software installed on Ubuntu (most recent -
20.04.1).

Most of these tools are hosted by 'efabless'. For more information, see:
https://opencircuitdesign.com

*** Open PDKS

The Open-PDKs project aims to collect the technology data for open and freely
available Process Development Kits for ASIC development.

It contains the technology and configuration files required to design an ASICS
for a particular fabrication process.

Download with:
#+begin_src sh
  git clone git://opencircuitdesign.com/open_pdks
#+end_src

*** Magic VLSI

Magic allows VLSI designs to be drawn by hand and exported to GDS format. It
does a lot more though, and can be used to check designs created by other means
against design rule constraints (DRC)

Install with the following (version 8.2.157)
#+begin_src sh
  sudo apt install magic
#+end_src

*** Electric

Electric is similar to Magic. Originally written in 'C' it has been ported to
Java and is available on other operating systems.

It also provides a 3D visualization option.

To install
#+begin_src sh
  sudo apt install electric
#+end_src

*** klayout

VLSI Layout software written in KDE

To install
#+begin_src sh
  sudo apt install klayout
#+end_src

** Examples

*** Editing gds with Magic
#+begin_src sh
  magic -T ../open_pdks/sky130/magic/sky130gds.tech gds/mawson-lakes-org.gds
#+end_src

or, to load the sky130 technology file separately, at the prompt in the magic
console, use:
#+begin_src tcl 
  tech load ../open_pdks/sky130/magic/sky130gds.tech
#+end_src

From the documentation, for the 'metal 1' layer
| Parameter    | Size       | Comment                         |
|--------------+------------+---------------------------------|
| Feature Size | 0.14 um    |                                 |
| Space Size   | 0.14 um    | Space between features          |
| Minimum Area | 0.083 um^2 | Equivalent to 0.28 um x 0.28 um |
